import fs from 'fs/promises';
import path from 'path';

export interface ExportOptions {
  format: 'markdown' | 'pdf' | 'html' | 'txt';
  includeTimestamps?: boolean;
  includeSteps?: boolean;
}

export interface VideoData {
  title: string;
  transcription: string;
  steps?: Array<{
    title: string;
    description: string;
    timestamp: number;
  }>;
  duration: number;
}

/**
 * Export video documentation to various formats
 */
export async function exportVideo(
  videoData: VideoData,
  options: ExportOptions
): Promise<string> {
  const uploadsDir = path.join(process.cwd(), 'uploads', 'exports');
  await fs.mkdir(uploadsDir, { recursive: true });

  const filename = `export_${Date.now()}.${options.format}`;
  const filepath = path.join(uploadsDir, filename);

  let content = '';

  switch (options.format) {
    case 'markdown':
      content = generateMarkdown(videoData, options);
      break;
    case 'html':
      content = generateHTML(videoData, options);
      break;
    case 'txt':
      content = generatePlainText(videoData, options);
      break;
    case 'pdf':
      content = generateMarkdown(videoData, options); // PDF would use markdown as base
      // In production, use a library like puppeteer or pdfkit
      break;
    default:
      throw new Error(`Unsupported format: ${options.format}`);
  }

  await fs.writeFile(filepath, content, 'utf-8');

  console.log(`✅ Exported to ${options.format}: ${filename}`);
  return filepath;
}

/**
 * Generate Markdown documentation
 */
function generateMarkdown(
  videoData: VideoData,
  options: ExportOptions
): string {
  let md = `# ${videoData.title}\n\n`;

  md += `**Duration:** ${formatDuration(videoData.duration)}\n\n`;
  md += `---\n\n`;

  if (options.includeSteps && videoData.steps) {
    md += `## Steps\n\n`;
    videoData.steps.forEach((step, index) => {
      md += `### Step ${index + 1}: ${step.title}\n\n`;
      md += `${step.description}\n\n`;
      if (options.includeTimestamps) {
        md += `*Timestamp: ${formatDuration(step.timestamp)}*\n\n`;
      }
    });
    md += `---\n\n`;
  }

  md += `## Transcription\n\n`;
  md += `${videoData.transcription}\n\n`;

  md += `---\n\n`;
  md += `*Generated by Screen Docs - Zero-Install Documentation Platform*\n`;

  return md;
}

/**
 * Generate HTML documentation
 */
function generateHTML(videoData: VideoData, options: ExportOptions): string {
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${videoData.title}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      color: #333;
    }
    h1 { color: #2563eb; border-bottom: 3px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #4b5563; margin-top: 30px; }
    h3 { color: #6b7280; }
    .meta { color: #6b7280; font-style: italic; }
    .step { background: #f3f4f6; padding: 15px; margin: 15px 0; border-radius: 8px; }
    .timestamp { color: #2563eb; font-size: 0.9em; }
    footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; text-align: center; }
  </style>
</head>
<body>
  <h1>${videoData.title}</h1>
  <p class="meta">Duration: ${formatDuration(videoData.duration)}</p>
  <hr>
`;

  if (options.includeSteps && videoData.steps) {
    html += `  <h2>Steps</h2>\n`;
    videoData.steps.forEach((step, index) => {
      html += `  <div class="step">\n`;
      html += `    <h3>Step ${index + 1}: ${step.title}</h3>\n`;
      html += `    <p>${step.description}</p>\n`;
      if (options.includeTimestamps) {
        html += `    <p class="timestamp">Timestamp: ${formatDuration(step.timestamp)}</p>\n`;
      }
      html += `  </div>\n`;
    });
  }

  html += `  <h2>Transcription</h2>\n`;
  html += `  <p>${videoData.transcription.replace(/\n/g, '<br>')}</p>\n`;

  html += `  <footer>
    <p>Generated by Screen Docs - Zero-Install Documentation Platform</p>
  </footer>
</body>
</html>`;

  return html;
}

/**
 * Generate plain text documentation
 */
function generatePlainText(
  videoData: VideoData,
  options: ExportOptions
): string {
  let txt = `${videoData.title}\n`;
  txt += `${'='.repeat(videoData.title.length)}\n\n`;
  txt += `Duration: ${formatDuration(videoData.duration)}\n\n`;

  if (options.includeSteps && videoData.steps) {
    txt += `STEPS\n-----\n\n`;
    videoData.steps.forEach((step, index) => {
      txt += `${index + 1}. ${step.title}\n`;
      txt += `   ${step.description}\n`;
      if (options.includeTimestamps) {
        txt += `   Timestamp: ${formatDuration(step.timestamp)}\n`;
      }
      txt += `\n`;
    });
  }

  txt += `TRANSCRIPTION\n-------------\n\n`;
  txt += `${videoData.transcription}\n\n`;

  txt += `---\n`;
  txt += `Generated by Screen Docs\n`;

  return txt;
}

/**
 * Format duration in seconds to readable format
 */
function formatDuration(seconds: number): string {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hrs > 0) {
    return `${hrs}:${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  }
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}
